CREATE TABLE AD_USERS ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     COMPANY VARCHAR2 (255 BYTE) , 
     COST_CENTER VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_LAST_UPDATE TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     EMAIL VARCHAR2 (255 BYTE) , 
     FAX VARCHAR2 (255 BYTE) , 
     FE_GROUP VARCHAR2 (255 BYTE) , 
     FE_ROLE VARCHAR2 (255 BYTE) , 
     FIRST_NAME VARCHAR2 (255 BYTE) , 
     LANGUAGE VARCHAR2 (255 BYTE) , 
     LAST_NAME VARCHAR2 (255 BYTE) , 
     PASSWORD VARCHAR2 (255 BYTE) , 
     PHONE VARCHAR2 (255 BYTE) , 
     SOURCE VARCHAR2 (255 BYTE) , 
     STATUS VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     USERNAME VARCHAR2 (255 BYTE) , 
     DEALER_CODE VARCHAR2 (255 BYTE) 
    );

CREATE TABLE ATTACHMENT ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     ATTACHMENT CLOB , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     FILENAME VARCHAR2 (2048 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) , 
     BULLETIN_ID NUMBER (19) 
    );

CREATE TABLE ATTACHMENT_HISTORY ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     ATTACHMENT_ID NUMBER (20) , 
     BULLETIN_ID NUMBER (20) , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     N_DOWNLOAD NUMBER (19) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) 
    );

CREATE TABLE BULLETIN ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     DE_CONTENT VARCHAR2 (255 BYTE) , 
     DE_DESCRIPTION VARCHAR2 (255 BYTE) , 
     DE_TITLE VARCHAR2 (255 BYTE) , 
     EN_CONTENT VARCHAR2 (255 BYTE) , 
     EN_DESCRIPTION VARCHAR2 (255 BYTE) , 
     EN_TITLE VARCHAR2 (255 BYTE) , 
     ES_CONTENT VARCHAR2 (255 BYTE) , 
     ES_DESCRIPTION VARCHAR2 (255 BYTE) , 
     ES_TITLE VARCHAR2 (255 BYTE) , 
     FR_CONTENT VARCHAR2 (255 BYTE) , 
     FR_DESCRIPTION VARCHAR2 (255 BYTE) , 
     FR_TITLE VARCHAR2 (255 BYTE) , 
     IT_CONTENT VARCHAR2 (255 BYTE) , 
     IT_DESCRIPTION VARCHAR2 (255 BYTE) , 
     IT_TITLE VARCHAR2 (255 BYTE) , 
     JP_CONTENT VARCHAR2 (255 BYTE) , 
     JP_DESCRIPTION VARCHAR2 (255 BYTE) , 
     JP_TITLE VARCHAR2 (255 BYTE) , 
     PRIORITY VARCHAR2 (20 BYTE) , 
     STATUS VARCHAR2 (20 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) , 
     ZH_CONTENT VARCHAR2 (255 BYTE) , 
     ZH_DESCRIPTION VARCHAR2 (255 BYTE) , 
     ZH_TITLE VARCHAR2 (255 BYTE) , 
     TECHAREA_ID NUMBER (19) 
    );

CREATE TABLE BULLETIN_CONTACT ( 
     BULLETIN_ID NUMBER (19)  NOT NULL , 
     EMAILCONTACT_ID NUMBER (19)  NOT NULL 
    );

CREATE TABLE BULLETIN_COUNTRY ( 
     BULLETIN_ID NUMBER (19)  NOT NULL , 
     ID_COUNTRY VARCHAR2 (255 BYTE)  NOT NULL 
    );

CREATE TABLE BULLETIN_DEALER ( 
     BULLETIN_ID NUMBER (19)  NOT NULL , 
     ID_DEALER VARCHAR2 (255 BYTE)  NOT NULL 
    );

CREATE TABLE BULLETIN_GEOAREA ( 
     BULLETIN_ID NUMBER (19)  NOT NULL , 
     ID_AREA VARCHAR2 (255 BYTE)  NOT NULL 
    );

CREATE TABLE BULLETIN_MAILINGLIST ( 
     BULLETIN_ID NUMBER (19)  NOT NULL , 
     MAILINGLIST_ID NUMBER (19)  NOT NULL 
    );

CREATE TABLE BULLETIN_REGION ( 
     BULLETIN_ID NUMBER (19)  NOT NULL ,
     ID_REGION VARCHAR2 (255 BYTE)  NOT NULL 
    );

CREATE TABLE BULLETIN_USER ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     DOWNLOAD NUMBER (1) DEFAULT 0 , 
     N_READ NUMBER (19) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_NAME VARCHAR2 (255 BYTE) , 
     USER_UPDATE VARCHAR2 (255 BYTE) , 
     BULLETIN_ID NUMBER (19) 
    );

CREATE TABLE DEALERS ( 
     ID VARCHAR2 (255 BYTE)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     ADDRESS VARCHAR2 (255 BYTE) , 
     CITY VARCHAR2 (255 BYTE) , 
     COMPLEMENT VARCHAR2 (255 BYTE) , 
     COUNTRY_CODE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DEALER_TYPE VARCHAR2 (255 BYTE) , 
     EMAIL VARCHAR2 (255 BYTE) , 
     FAX VARCHAR2 (255 BYTE) , 
     FLAG_AFTERMARKET VARCHAR2 (255 BYTE) , 
     FLAG_ALLUMINIUM VARCHAR2 (255 BYTE) , 
     FLAG_ASSISTANCE VARCHAR2 (255 BYTE) , 
     FLAG_BODYSHOP VARCHAR2 (255 BYTE) , 
     FLAG_DEALER VARCHAR2 (255 BYTE) , 
     FLAG_DEALERSELECTION VARCHAR2 (255 BYTE) , 
     FLAG_EUROPEASS VARCHAR2 (255 BYTE) , 
     FLAG_FLAGSHIP VARCHAR2 (255 BYTE) , 
     FLAG_HVR VARCHAR2 (255 BYTE) , 
     FLAG_IMPORTER VARCHAR2 (255 BYTE) , 
     FLAG_PDICENTER VARCHAR2 (255 BYTE) , 
     FLAG_POS VARCHAR2 (255 BYTE) , 
     FLAG_REGIONALOFFICE VARCHAR2 (255 BYTE) , 
     FLAG_REGIONALOFFICE_SUBSIDIARY VARCHAR2 (255 BYTE) , 
     FLAG_SHOWROOM VARCHAR2 (255 BYTE) , 
     FLAG_SUBDEALER VARCHAR2 (255 BYTE) , 
     FLAG_SUBSIDIARY VARCHAR2 (255 BYTE) , 
     GL_LATITUDE NUMBER (38) , 
     GL_LONGITUDE NUMBER (38) , 
     HOUSE_NUMBER VARCHAR2 (255 BYTE) , 
     NAME VARCHAR2 (255 BYTE) , 
     PHONE VARCHAR2 (255 BYTE) , 
     PROVINCE VARCHAR2 (255 BYTE) , 
     PROVINCE_CODE VARCHAR2 (255 BYTE) , 
     SW_ENABLED VARCHAR2 (255 BYTE) , 
     SW_HEADING NUMBER (38) , 
     SW_LATITUDE NUMBER (38) , 
     SW_LONGITUDE NUMBER (38) , 
     SW_PITCH NUMBER (38) , 
     SW_ZOOM NUMBER (38) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     VILLAGE VARCHAR2 (255 BYTE) , 
     WEBSITE VARCHAR2 (255 BYTE) , 
     ZIPCODE VARCHAR2 (255 BYTE) 
    );

CREATE TABLE DEALER_ROLES ( 
     ID NUMBER (19)  NOT NULL , 
     ROLE VARCHAR2 (255 BYTE)  NOT NULL 
    );

CREATE TABLE DEPARTMENT ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     NAME VARCHAR2 (255 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) 
    );

CREATE TABLE EMAIL_CONTACT ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     COUNTRY VARCHAR2 (255 BYTE) , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     EMAIL VARCHAR2 (255 BYTE) , 
     NAME VARCHAR2 (255 BYTE) , 
     ROLE VARCHAR2 (255 BYTE) , 
     SURNAME VARCHAR2 (255 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) 
    );

CREATE TABLE GEO_AREAS ( 
     ID VARCHAR2 (255 BYTE)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DESCRIPTION_DE VARCHAR2 (255 BYTE) , 
     DESCRIPTION_EN VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ES VARCHAR2 (255 BYTE) , 
     DESCRIPTION_FR VARCHAR2 (255 BYTE) , 
     DESCRIPTION_IT VARCHAR2 (255 BYTE) , 
     DESCRIPTION_JP VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ZH VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) 
    );

CREATE TABLE GEO_COUNTRIES ( 
     ID VARCHAR2 (255 BYTE) NOT NULL , 
     ID_ISO3166 VARCHAR2 (255 BYTE) ,
     ID_ISO3166_3 VARCHAR2 (255 BYTE) ,
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DESCRIPTION_DE VARCHAR2 (255 BYTE) , 
     DESCRIPTION_EN VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ES VARCHAR2 (255 BYTE) , 
     DESCRIPTION_FR VARCHAR2 (255 BYTE) , 
     DESCRIPTION_IT VARCHAR2 (255 BYTE) , 
     DESCRIPTION_JP VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ZH VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     ID_REGION VARCHAR2 (255 BYTE) 
    );

CREATE TABLE GEO_REGIONS ( 
     ID VARCHAR2 (255 BYTE)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DESCRIPTION_DE VARCHAR2 (255 BYTE) , 
     DESCRIPTION_EN VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ES VARCHAR2 (255 BYTE) , 
     DESCRIPTION_FR VARCHAR2 (255 BYTE) , 
     DESCRIPTION_IT VARCHAR2 (255 BYTE) , 
     DESCRIPTION_JP VARCHAR2 (255 BYTE) , 
     DESCRIPTION_ZH VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     ID_AREA VARCHAR2 (255 BYTE) 
    );

CREATE TABLE MAILING_EMAIL ( 
     EMAILCONTACT_ID NUMBER (19)  NOT NULL , 
     MAILINGLIST_ID NUMBER (19)  NOT NULL 
    );

CREATE TABLE MAILING_LIST ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     NAME VARCHAR2 (255 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) 
    );

CREATE TABLE ROLES_ACTION ( 
     ID NUMBER (19)  NOT NULL , 
     ACTION VARCHAR2 (255 BYTE) , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     ROLES VARCHAR2 (255 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) 
    );

CREATE TABLE TAG ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) , 
     WORD VARCHAR2 (255 BYTE) , 
     BULLETIN_ID NUMBER (19) 
    );

CREATE TABLE TECH_AREA_DEPT ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE NUMBER (1) DEFAULT 0 , 
     CREATE_DATE TIMESTAMP  NOT NULL , 
     NAME VARCHAR2 (255 BYTE) , 
     UPDATE_DATE TIMESTAMP , 
     USER_CREATE VARCHAR2 (255 BYTE)  NOT NULL , 
     USER_UPDATE VARCHAR2 (255 BYTE) , 
     DEPARTMENT_ID NUMBER (19) 
    );

CREATE TABLE USER_DEALER_ROLES ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     LANGUAGE VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     USERNAME VARCHAR2 (255 BYTE)  NOT NULL , 
     AD_USERS_ID NUMBER (19) , 
     DEALER_ROLES_ID NUMBER (19) , 
     TECH_AREA_DEPT_ID NUMBER (19) 
    );

CREATE TABLE VEHICLE_FAMILY ( 
     ID VARCHAR2 (255 BYTE)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DESCRIPTION VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) 
    );

CREATE TABLE VEHICLE_GROUPS ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DCS_CATALOG_RELEASE NUMBER (38) , 
     DCS_CATALOG_VERSION NUMBER (38) , 
     DCS_MODEL VARCHAR2 (255 BYTE) , 
     DCS_VEHICLECLASS VARCHAR2 (255 BYTE) , 
     DESCRIPTION VARCHAR2 (255 BYTE) , 
     MODEL VARCHAR2 (255 BYTE) , 
     PROJECT_ID NUMBER (38) , 
     SUSPENDED VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     FAMILY_CODE VARCHAR2 (255 BYTE) 
    );

CREATE TABLE VEHICLE_MASTER ( 
     ID NUMBER (19)  NOT NULL , 
     ACTIVE VARCHAR2 (255 BYTE) , 
     DATE_INS TIMESTAMP , 
     DATE_MOD TIMESTAMP , 
     DESCRIPTION VARCHAR2 (255 BYTE) , 
     FLAG_CHALLENGE VARCHAR2 (255 BYTE) , 
     USER_INS VARCHAR2 (255 BYTE) , 
     USER_MOD VARCHAR2 (255 BYTE) , 
     VEHICLE_GROUP_ID NUMBER (19) 
    );