ALTER TABLE AD_USERS 
    ADD CONSTRAINT AD_USERS_PK PRIMARY KEY ( ID );
	
ALTER TABLE ATTACHMENT 
    ADD CONSTRAINT ATTACHMENT_PK PRIMARY KEY ( ID );	
	
ALTER TABLE ATTACHMENT_HISTORY 
    ADD CONSTRAINT ATTACHMENT_HISTORY_PK PRIMARY KEY ( ID );	

ALTER TABLE BULLETIN 
    ADD CONSTRAINT BULLETIN_PK PRIMARY KEY ( ID );	

ALTER TABLE BULLETIN_CONTACT 
    ADD CONSTRAINT BULLETIN_CONTACT_PK PRIMARY KEY ( BULLETIN_ID, EMAILCONTACT_ID );

ALTER TABLE BULLETIN_COUNTRY 
    ADD CONSTRAINT BULLETIN_COUNTRY_PK PRIMARY KEY ( BULLETIN_ID, ID_COUNTRY );

ALTER TABLE BULLETIN_DEALER 
    ADD CONSTRAINT BULLETIN_DEALER_PK PRIMARY KEY ( BULLETIN_ID, ID_DEALER );

ALTER TABLE BULLETIN_GEOAREA 
    ADD CONSTRAINT BULLETIN_GEOAREA_PK PRIMARY KEY ( BULLETIN_ID, ID_AREA );

ALTER TABLE BULLETIN_MAILINGLIST 
    ADD CONSTRAINT BULLETIN_MAILINGLIST_PK PRIMARY KEY ( BULLETIN_ID, MAILINGLIST_ID );

ALTER TABLE BULLETIN_REGION 
    ADD CONSTRAINT BULLETIN_REGION_PK PRIMARY KEY ( BULLETIN_ID, ID_REGION );

ALTER TABLE BULLETIN_USER 
    ADD CONSTRAINT BULLETIN_USER_PK PRIMARY KEY ( ID );

ALTER TABLE DEALERS 
    ADD CONSTRAINT DEALERS_PK PRIMARY KEY ( ID );

ALTER TABLE DEALER_ROLES 
    ADD CONSTRAINT DEALER_ROLES_PK PRIMARY KEY ( ID );

ALTER TABLE DEPARTMENT 
    ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY ( ID );

ALTER TABLE EMAIL_CONTACT 
    ADD CONSTRAINT EMAIL_CONTACT_PK PRIMARY KEY ( ID );

ALTER TABLE GEO_AREAS 
    ADD CONSTRAINT GEO_AREAS_PK PRIMARY KEY ( ID );

ALTER TABLE GEO_COUNTRIES 
    ADD CONSTRAINT GEO_COUNTRIES_PK PRIMARY KEY ( ID );

ALTER TABLE GEO_REGIONS 
    ADD CONSTRAINT GEO_REGIONS_PK PRIMARY KEY ( ID );

ALTER TABLE MAILING_EMAIL 
    ADD CONSTRAINT MAILING_EMAIL_PK PRIMARY KEY ( EMAILCONTACT_ID, MAILINGLIST_ID );

ALTER TABLE MAILING_LIST 
    ADD CONSTRAINT MAILING_LIST_PK PRIMARY KEY ( ID );

ALTER TABLE ROLES_ACTION 
    ADD CONSTRAINT ROLES_ACTION_PK PRIMARY KEY ( ID );

ALTER TABLE TAG 
    ADD CONSTRAINT TAG_PK PRIMARY KEY ( ID );

ALTER TABLE TECH_AREA_DEPT 
    ADD CONSTRAINT TECH_AREA_DEPT_PK PRIMARY KEY ( ID );

ALTER TABLE USER_DEALER_ROLES 
    ADD CONSTRAINT USER_DEALER_ROLES_PK PRIMARY KEY ( ID );

ALTER TABLE VEHICLE_FAMILY 
    ADD CONSTRAINT VEHICLE_FAMILY_PK PRIMARY KEY ( ID );

ALTER TABLE VEHICLE_GROUPS 
    ADD CONSTRAINT VEHICLE_GROUP_PK PRIMARY KEY ( ID );

ALTER TABLE VEHICLE_MASTER 
    ADD CONSTRAINT VEHICLE_MASTER_PK PRIMARY KEY ( ID );

ALTER TABLE BULLETIN_MAILINGLIST 
    ADD CONSTRAINT BLLETINMAILINGLISTMILINGLISTID FOREIGN KEY ( 
     MAILINGLIST_ID
    ) 
    REFERENCES MAILING_LIST ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_CONTACT 
    ADD CONSTRAINT BULLETINCONTACTEMAILCONTACT_ID FOREIGN KEY ( 
     EMAILCONTACT_ID
    ) 
    REFERENCES EMAIL_CONTACT ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_MAILINGLIST 
    ADD CONSTRAINT BULLETINMAILINGLISTBULLETIN_ID FOREIGN KEY ( 
     BULLETIN_ID
    ) 
    REFERENCES BULLETIN ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_CONTACT 
    ADD CONSTRAINT BULLETIN_CONTACT_BULLETIN_ID FOREIGN KEY ( 
     BULLETIN_ID
    ) 
    REFERENCES BULLETIN ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_COUNTRY 
    ADD CONSTRAINT BULLETIN_COUNTRY_BULLETIN_ID FOREIGN KEY ( 
     BULLETIN_ID
    ) 
    REFERENCES BULLETIN ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_GEOAREA 
    ADD CONSTRAINT BULLETIN_GEOAREA_BULLETIN_ID FOREIGN KEY ( 
     BULLETIN_ID
    ) 
    REFERENCES BULLETIN ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE AD_USERS 
    ADD CONSTRAINT FK_AD_USERS_DEALER_CODE FOREIGN KEY ( 
     DEALER_CODE
    ) 
    REFERENCES DEALERS ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE ATTACHMENT 
    ADD CONSTRAINT FK_ATTACHMENT_BULLETIN_ID FOREIGN KEY ( 
     BULLETIN_ID
    ) 
    REFERENCES BULLETIN ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_COUNTRY 
    ADD CONSTRAINT FK_BULLETIN_COUNTRY_COUNTRY_ID FOREIGN KEY ( 
     ID_COUNTRY
    ) 
    REFERENCES GEO_COUNTRIES ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_DEALER 
    ADD CONSTRAINT FK_BULLETIN_DEALER_BULLETIN_ID FOREIGN KEY ( 
     BULLETIN_ID
    ) 
    REFERENCES BULLETIN ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_DEALER 
    ADD CONSTRAINT FK_BULLETIN_DEALER_ID_DEALER FOREIGN KEY ( 
     ID_DEALER
    ) 
    REFERENCES DEALERS ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_GEOAREA 
    ADD CONSTRAINT FK_BULLETIN_GEOAREA_ID_AREA FOREIGN KEY ( 
     ID_AREA
    ) 
    REFERENCES GEO_AREAS ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_REGION 
    ADD CONSTRAINT FK_BULLETIN_REGION_ID_REGION FOREIGN KEY ( 
     ID_REGION
    ) 
    REFERENCES GEO_REGIONS ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN 
    ADD CONSTRAINT FK_BULLETIN_TECHAREA_ID FOREIGN KEY ( 
     TECHAREA_ID
    ) 
    REFERENCES TECH_AREA_DEPT ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE BULLETIN_USER 
    ADD CONSTRAINT FK_BULLETIN_USER_BULLETIN_ID FOREIGN KEY ( 
     BULLETIN_ID
    ) 
    REFERENCES BULLETIN ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE GEO_COUNTRIES 
    ADD CONSTRAINT FK_GEO_COUNTRIES_ID_REGION FOREIGN KEY ( 
     ID_REGION
    ) 
    REFERENCES GEO_REGIONS ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE GEO_REGIONS 
    ADD CONSTRAINT FK_GEO_REGIONS_ID_AREA FOREIGN KEY ( 
     ID_AREA
    ) 
    REFERENCES GEO_AREAS ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE TAG 
    ADD CONSTRAINT FK_TAG_BULLETIN_ID FOREIGN KEY ( 
     BULLETIN_ID
    ) 
    REFERENCES BULLETIN ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE VEHICLE_GROUPS 
    ADD CONSTRAINT FK_VEHICLE_GROUP_FAMILY_CODE FOREIGN KEY ( 
     DCS_MODEL
    ) 
    REFERENCES VEHICLE_FAMILY ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE MAILING_EMAIL 
    ADD CONSTRAINT MAILING_EMAIL_EMAILCONTACT_ID FOREIGN KEY ( 
     EMAILCONTACT_ID
    ) 
    REFERENCES EMAIL_CONTACT ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE MAILING_EMAIL 
    ADD CONSTRAINT MAILING_EMAIL_MAILINGLIST_ID FOREIGN KEY ( 
     MAILINGLIST_ID
    ) 
    REFERENCES MAILING_LIST ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE TECH_AREA_DEPT 
    ADD CONSTRAINT TECH_AREA_DEPT_DEPARTMENT_ID FOREIGN KEY ( 
     DEPARTMENT_ID
    ) 
    REFERENCES DEPARTMENT ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE USER_DEALER_ROLES 
    ADD CONSTRAINT USERDEALERROLESDEALER_ROLES_ID FOREIGN KEY ( 
     DEALER_ROLES_ID
    ) 
    REFERENCES DEALER_ROLES ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE USER_DEALER_ROLES 
    ADD CONSTRAINT USERDEALERROLESTECHAREADEPT_ID FOREIGN KEY ( 
     TECH_AREA_DEPT_ID
    ) 
    REFERENCES TECH_AREA_DEPT ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE USER_DEALER_ROLES 
    ADD CONSTRAINT USER_DEALER_ROLES_AD_USERS_ID FOREIGN KEY ( 
     AD_USERS_ID
    ) 
    REFERENCES AD_USERS ( 
     ID
    ) 
    NOT DEFERRABLE;

ALTER TABLE VEHICLE_MASTER 
    ADD CONSTRAINT VEHICLE_MASTERVEHICLE_GROUP_ID FOREIGN KEY ( 
     VEHICLE_GROUP_ID
    ) 
    REFERENCES VEHICLE_GROUPS ( 
     ID
    ) 
    NOT DEFERRABLE;
	