grant ALTER, DELETE, INDEX, INSERT, UPDATE, SELECT, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK on "DEALERS" to "MBORDIN" ;
grant ALTER, DELETE, INDEX, INSERT, UPDATE, SELECT, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK on "AD_USERS" to "MBORDIN" ;
grant ALTER, DELETE, INDEX, INSERT, UPDATE, SELECT, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK on "GEO_AREAS" to "MBORDIN" ;
grant ALTER, DELETE, INDEX, INSERT, UPDATE, SELECT, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK on "GEO_REGIONS" to "MBORDIN" ;
grant ALTER, DELETE, INDEX, INSERT, UPDATE, SELECT, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK on "GEO_COUNTRIES" to "MBORDIN" ;
grant ALTER, DELETE, INDEX, INSERT, UPDATE, SELECT, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK on "VEHICLE_FAMILY" to "MBORDIN" ;
grant ALTER, DELETE, INDEX, INSERT, UPDATE, SELECT, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK on "VEHICLE_GROUPS" to "MBORDIN" ;
grant ALTER, DELETE, INDEX, INSERT, UPDATE, SELECT, REFERENCES, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK on "VEHICLE_MASTER" to "MBORDIN" ;